// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeR0FuthfHhmNg221oGLzY6f8vBBqRQmc',
    appId: '1:1081014321686:web:73f179db5c144f37386b37',
    messagingSenderId: '1081014321686',
    projectId: 'pariwisata-cireong',
    authDomain: 'pariwisata-cireong.firebaseapp.com',
    storageBucket: 'pariwisata-cireong.appspot.com',
    measurementId: 'G-ZGYP2QXW1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYmncvKVm41GP5nENKXF3IQkrdXdr6dbI',
    appId: '1:1081014321686:android:b877e2d3cf6b9a1b386b37',
    messagingSenderId: '1081014321686',
    projectId: 'pariwisata-cireong',
    storageBucket: 'pariwisata-cireong.appspot.com',
  );
}
